
@host = http://localhost:3000

@urlUsers = /api/users
@urlClients = /api/clients
@urlReparations = /api/reparations
@urlCars = /api/cars
@urlMechanics = /api/mechanics

### API DE USUARIOS (ADMIN)


# ### GET BY ID
# GET {{host}}{{urlUsers}}/11
# Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMywiZXhwIjoxNjg4NDYxNDg0LCJpYXQiOjE2ODE1NDk0ODR9.ifmy-xfFTuogqkEl4zbXhSuKsYfDQBnv0k98vwKgkM8

# ### GET BY DNI
# GET {{host}}{{urlUsers}}/dni/TEST556
# Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOSwiZXhwIjoxNjg4NjI0Mjc0LCJpYXQiOjE2ODE3MTIyNzR9.RYSAHldxuHLFYLukClwzGrCOjKzletdMtCE5KzeaeOo


# ### GET BY EMAIL
# GET {{host}}{{urlUsers}}/email/sara@
# Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMywiZXhwIjoxNjg4NDYxNDg0LCJpYXQiOjE2ODE1NDk0ODR9.ifmy-xfFTuogqkEl4zbXhSuKsYfDQBnv0k98vwKgkM8


### NEW USER
POST {{host}}{{urlUsers}}/register
Content-Type: application/json

{
    "name": "Lula",
    "surname": "Martin",
    "birthdate": "1966-10-21",
    "dni": "213452",
    "phone": "6432145",
    "email": "lula@",
    "username": "lula",
    "password": "12345",
    "role": "admin"
}


### LOGIN USER
POST {{host}}{{urlUsers}}/login
Content-Type: application/json

{
    "email": "lula@",
    "dni" : "0897430984",
    "password": "1234"
}


### GET ADMIN EMPLOYERS
GET {{host}}{{urlUsers}}/admins


### GET ADMIN EMPLOYERS BY ID
GET {{host}}{{urlUsers}}/admins/1


### EDIT USER
PUT {{host}}{{urlUsers}}/edit/40
Content-Type: application/json

{
    "name": "Lula",
    "surname": "Romero",
    "birthdate": "1967-10-13",
    "dni": "71254837O2",
    "phone": "661542362",
    "email": "lula2@",
    "username": "Lula",
    "password": "12345"
}


### DELETE ADMIN EMPLOYER
DELETE {{host}}{{urlUsers}}/admin/13

###################################################


### API DE CLIENTES


### NEW CLIENT
POST {{host}}{{urlClients}}
Content-Type: application/json

{
    "name": "Alberto",
    "surname": "Contreras",
    "email":"alberto@",
    "phone": "765442383",
    "dni": "9876451096",
    "address": "Plaza Mayor, 23",
    "card_number": 615453947
}

### GET ALL
GET {{host}}{{urlClients}}


### GET BY ID
GET {{host}}{{urlClients}}/8


### GET CAR OF CLIENT
GET {{host}}{{urlClients}}/car/20


### DELETE CLIENT BY ID
DELETE {{host}}{{urlClients}}/11


//FIXME: EMAIL OR DNI EN USERS



###################################################


### API DE REPARACIONES

### POST REPARATION
POST {{host}}{{urlReparations}}
Content-Type: application/json

{
    "type": "mechanic",
    "reparation":"revision",
    "price": "200",
    "users_id": 40,
    "cars_id": 9
}



### GET ALL REPARATIONS
GET {{host}}{{urlReparations}}


### GET BY ID
GET {{host}}{{urlReparations}}/4


### GET MECHANIC OF THIS REPARATION
GET {{host}}{{urlReparations}}/mechanic/


### EDIT REPARATION
PUT {{host}}{{urlReparations}}/edit/19
Content-Type: application/json

 {
    "status": "in_progress",
    "type": "mechanic",
    "reparation":"need revision",
    "price": "200",
    "users_id": 40
    
}


### DELETE REPARATION

DELETE {{host}}{{urlReparations}}/3


##################################################

### API DE COCHES

### POST CAR
POST {{host}}{{urlCars}}
Content-Type: application/json

{  
    "chasis": "432546",
    "registration": "453635",
    "brand":"MERCEDES",
    "model": "S 500",
    "color": "black",
    "km": 78975,
    "year": 2020,
    "doors": 5,
    "type": "automatic",
    "fuel": "gasoil",
    "damages": "Change neumatics",
    "clients_id": 3
}


### GET ALL CARS
GET {{host}}{{urlCars}}


###GET CAR BY ID
GET {{host}}{{urlCars}}/1


### GET CAR BY CLIENT
GET {{host}}{{urlCars}}/client/1

### EDIT CAR BY ID
PUT {{host}}{{urlCars}}/1
Content-Type: application/json

{  
    "chasis": "432546",
    "registration": "453635",
    "brand":"MERCEDES",
    "model": "S 500",
    "color": "black",
    "km": 78975,
    "year": 2020,
    "doors": 5,
    "type": "automatic",
    "fuel": "gasoil",
    "damages": "Change neumatics",
}

### DELETE CAR BY ID
DELETE {{host}}{{urlCars}}/4

##############################################

### GET ALL MECHANICS

### GET ALL
GET {{host}}{{urlMechanics}}


### GET BY ID
GET {{host}}{{urlMechanics}}/25


### DELETE MECHANIC BY ID
DELETE {{host}}{{urlMechanics}}/25
