
@host = http://localhost:3000

@urlUsers = /api/users
@urlClients = /api/clients
@urlReparations = /api/reparations
@urlCars = /api/cars
@urlMechanics = /api/mechanics

### API DE USUARIOS (ADMIN Y MECHANIC)
//Cuando hacemos login vamos a la interfaz de admin o clientes segun el login que hagamos, en users creo que solo habria que sacar cada user por id, mail, dni. Borrar por id. 


### GET ALL USERS
GET {{host}}{{urlUsers}}


### GET BY ID
GET {{host}}{{urlUsers}}/11
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMywiZXhwIjoxNjg4NDYxNDg0LCJpYXQiOjE2ODE1NDk0ODR9.ifmy-xfFTuogqkEl4zbXhSuKsYfDQBnv0k98vwKgkM8

### GET BY DNI
GET {{host}}{{urlUsers}}/dni/TEST556
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOSwiZXhwIjoxNjg4NjI0Mjc0LCJpYXQiOjE2ODE3MTIyNzR9.RYSAHldxuHLFYLukClwzGrCOjKzletdMtCE5KzeaeOo


### GET BY EMAIL
GET {{host}}{{urlUsers}}/email/test55
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMywiZXhwIjoxNjg4NDYxNDg0LCJpYXQiOjE2ODE1NDk0ODR9.ifmy-xfFTuogqkEl4zbXhSuKsYfDQBnv0k98vwKgkM8


# ### GET BY DNI OR EMAIL
# GET {{host}}{{urlUsers}}/mixto/TEST55


### DELETE USER BY ID
DELETE {{host}}{{urlUsers}}/16
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMywiZXhwIjoxNjg4NDYxNDg0LCJpYXQiOjE2ODE1NDk0ODR9.ifmy-xfFTuogqkEl4zbXhSuKsYfDQBnv0k98vwKgkM8


### NEW USER
POST {{host}}{{urlUsers}}/register
Content-Type: application/json

{
    "name": "Test65",
    "surname": "Test65",
    "birthdate": "1996-10-21",
    "dni": "TEST5564",
    "phone": "TEST5564",
    "email": "TEST5564",
    "username": "TEST564",
    "password": "123454",
    "role": "admin"
}


### LOGIN USER
POST {{host}}{{urlUsers}}/login
Content-Type: application/json

{
    "email": "TEST556",
    "password": "12345"
}


###################################################


### API DE CLIENTES
//Cuando accedemos a los clientes podemos: VER TODOS, VER UNO, CREAR y BORRAR POR ID
//MODIFICAR??

### NEW CLIENT
POST {{host}}{{urlClients}}
Content-Type: application/json

{
    "name": "Eugenia",
    "surname": "Contreras",
    "email":"eu@gmail.com",
    "phone": "76541813",
    "dni": "987641096",
    "address": "Plaza Mayor, 23",
    "card_number": 6153947
}

### GET ALL
GET {{host}}{{urlClients}}


### GET BY ID
GET {{host}}{{urlClients}}/8


### DELETE BY ID
DELETE {{host}}{{urlClients}}/5


//FIXME: EMAIL OR DNI EN USERS



###################################################


### API DE REPARACIONES

### POST REPARATION
POST {{host}}{{urlReparations}}
Content-Type: application/json

{
    "status": "in_progress",
    "type": "mechanic",
    "reparation":"xxx",
    "price": "200",
    "users_id": 11,
    "cars_id": 1
}



### GET ALL REPARATIONS
GET {{host}}{{urlReparations}}


### GET BY ID
GET {{host}}{{urlReparations}}/2

###################################################


### API DE COCHES

### POST CAR
POST {{host}}{{urlCars}}
Content-Type: application/json

{  
    "chasis": "432546",
    "registration": "453635",
    "brand":"MERCEDES",
    "model": "S 500",
    "color": "black",
    "km": 78975,
    "year": 2020,
    "doors": 5,
    "type": "automatic",
    "fuel": "gasoil",
    "damages": "Change neumatics",
    "clients_id": 3
}


### GET ALL CARS
GET {{host}}{{urlCars}}

###GET CAR BY ID
GET {{host}}{{urlCars}}/1



##############################################

### GET ALL MECHANICS

### GET ALL
GET {{host}}{{urlMechanics}}


### GET BY ID
GET {{host}}{{urlMechanics}}/25